name: App Pipeline

on:
  push:
    branches:
      - main
    paths:
      - app/**


permissions:
  contents: read
  id-token: write

jobs:
  app-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app
    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name azure-project1 

      - name: Build, tag, and push image to Azure ACR
        env:
          ACR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ACR_REPOSITORY: flaskapp
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG .
          docker push $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG
