name:  infrastructure pipeline

run-name: Infrastructure Pipeline by ${{ github.actor }} 

on:
  push:
    branches:
      - main
    paths:
      - terraform/**

  workflow_dispatch: 

concurrency:
  group: terraform-azure
  cancel-in-progress: false
  
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_key_vault_secret_id: ${{ vars.KEY_VAULT_SECRET_ID }}


    defaults:
      run:
        working-directory: terraform
    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform fmt
        working-directory: terraform
        run: terraform fmt

      - name: tflint
        uses: terraform-linters/setup-tflint@v4

      - name: run checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform
          
        
       # with:
        #  hard_fail_on: 

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve